### ISSUE TITLE
Explorar herramientas para prototipos de UI

### ISSUE THREAD

**Issue by montanez8** [montanez8/codeCreatorsTeam#11]

**Comment by jorgeAfrancoA** [comment]
[DiagramasSprint1.pptx](https://github.com/montanez8/codeCreatorsTeam/files/9440376/DiagramasSprint1.pptx)

**Comment by jorgeAfrancoA** [comment]
Listo Carlos, ahi están los tres diagramas: Caso de estudio. diagrama de clases y Hogar Gestor App
