### ISSUE TITLE
reunión de planeación.

### ISSUE THREAD

**Issue by montanez8** [montanez8/codeCreatorsTeam#22]

**Comment by jorgeAfrancoA** [comment]
![image](https://user-images.githubusercontent.com/111654414/188277782-71cd2a9b-a6f2-4255-8d9c-ede1a32d799c.png)
[Sprint2.pptx](https://github.com/montanez8/codeCreatorsTeam/files/9482922/Sprint2.pptx)

**Comment by jorgeAfrancoA** [comment]
Buenos dias compañeros, ahi les comparto lo realizado hasta hoy. La solución está funcionando bien hasta donde vamos con el profe
