### ISSUE TITLE
Explorar herramienta para prototipos de UI

### ISSUE THREAD

**Issue by montanez8** [montanez8/codeCreatorsTeam#4]

**Comment by jorgeAfrancoA** [comment]
[HogarGestorGitHub,.pptx](https://github.com/montanez8/codeCreatorsTeam/files/9410916/HogarGestorGitHub.pptx)

Buenas tardes compañeros, ahí se actualizó la tarea

**Comment by jorgeAfrancoA** [comment]
Buenas tardes compañeros, ahí se actualizó la tarea
